### PR TITLE
Replace loop by jobqueue to prevent memory overflow and applicationcrash

### PR DESCRIPTION
**Pull request by TimvanSteenbergen**
Yesterday our system crashed because of a memoryleak triggered by our jobqueue-list containing 1.2 million Done jobs and never having cleaned up and someone pushing the button 'Clean', triggering ACT_CleanJobs, which exploded the boobytrap of the loop that keeps all the data of each looprun in memory until the microflow is done.

This is now replaced by putting each delete on the queue :-) Please have a look. Appreciated if you make another (last probably) release in which this memory overflow is no longer possible.

NB. We also prevented the queue job keeping finding its own job by the decision 'At least 100 jobs found' and never stop.

### CODE REVIEW

**Comment by TimvanSteenbergen** [comment]
Btw, only change is in ACT_CleanJobs

**Comment by TimvanSteenbergen** [comment]
And one important question is: is this loop also present in Mendix 9? If so, can you do something to repair that

**Comment by JaapvanLeeuwen** [comment]
Excellent usecase of when to use the queue indeed. I'll merge it right away and release it soon.
About your question regarding Mendix 9 - If I'm not mistaken v8.12 is the minimum requirement for importing it into mendix 9. I've tested and released that before too.
Since Mendix introduced their own task queue in Mendix 9 we decided not to further develop this module apart from bug fixes. Unless we find a good reason to further develop this module, we'll switch to the platform supported module (at least for the time being).

**Comment by tmisker** [comment]
Nice addition, we also run into this.
However, the 'Delete all' now relies on a queue 'JobsToDelete', which is not initialised by default.

**Pull request merged**
